### ISSUE TITLE
Consider changing all TIMESTAMPs to time.time()

### ISSUE THREAD

**Issue by reginafcompton** [brighthive/authserver#5]
Currently, the Authserver stores dates/times using two different formats:

1. [`TIMESTAMP` from sqlalchemy](https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.TIMESTAMP) – used for six fields, in the DataTrust, Role, and User models.
2. `time.time()` – [inherited from the OAuth2ClientMixin](https://github.com/lepture/authlib/blob/994e306d608291dd459ab706881484102d2a9442/authlib/flask/oauth2/sqla.py#L19-L22)

On the Facet side, it would be nice to only worry about transforming one data type. 

Also on the Facet side, the `Epoch` timestamp in UTC seems (a little) easier to deal with in JavaScript. (Basically, it comes down to transforming a string with a non-specific timezone vs. an integer with a precisely known timezone.)

@gregmundy - are you opposed to using an Integer field (`time.time()`) for all timestamps?

**Comment by reginafcompton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a Facet user, I want to see timezone-sensitive timestamps (or at least know the time zone of the timestamp).](https://trello.com/c/afIUzbnI/88-as-a-facet-user-i-want-to-see-timezone-sensitive-timestamps-or-at-least-know-the-time-zone-of-the-timestamp)

**Comment by gregmundy** [comment]
@reginafcompton All timestamps are in UTC, wouldn't it be easier to simply have Facet convert the timestamp to whatever timezone you prefer?

**Comment by reginafcompton** [comment]
@gregmundy - this issue does not concern the timezone per se (though it's related!). I am more concerned with having Facet handle both Epoch timestamps (which come from OauthClient mixin) and the human-readable timestamps from Sqlalchemy. (I am asking if we can change all timestamps to Epoch.)

Facet can mange both. But, I figure I may as well be a greedy front-end dev and ask for timestamps to be consistent across fields.

**Comment by reginafcompton** [comment]
We might need to refactor some of the API code, e.g., modifying some of the actual queries. (Plus, we do not need Epoch precision for things like last_updated.) It is not worth the effort to make modifications here! Time will be better spent doing the work on the client side.
